spring.application.name=territorios

server.servlet.context-path=/territorios/api
springdoc.swagger-ui.path=/swagger-ui.html

server.port=${PORT:8080}

#DATABASE

spring.jpa.database=postgresql
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
