spring.application.name=territorios

server.servlet.context-path=/territorios/api
springdoc.swagger-ui.path=/swagger-ui.html

server.port=${PORT:8080}

#DATABASE

spring.jpa.database=postgresql
spring.datasource.url=jdbc:postgresql://dboik.postgres.database.azure.com:5432/postgres?sslmode=require
spring.datasource.username=adminok
spring.datasource.password=Nippon0703
